language: c

dist: xenial

compiler:
  - gcc
  - clang

install:
  - curl --silent --location \
    https://raw.githubusercontent.com/groonga/groonga/master/data/travis/setup.sh | sh
  - travis/friso.sh

before_script:
  - ./autogen.sh
  - ./configure --with-friso-ini=/usr/local/etc/friso.ini
  - make

script:
  - test/run-test.sh
